### ISSUE TITLE
comments- no grade yet

### ISSUE THREAD

**Issue by timm** [ankitkumar93/csc510-se-project#1]
Thanks for turning in ahead of time-- well done!

I can see the wheels spinning but its not clear to me that you probed your domain deep enough to get the insights needed to guide your February work, or demonstrate success (or otherwise)  by March 30.

That said, it could be that the ideas are forming in your head and great stuff will follow. So please carry on and his this as the basis for your work for the next two months.

**Comment by ashutoshchaturvedi** [comment]
Thanks for the feedback.
