### ISSUE TITLE
data storage in plugin

### ISSUE THREAD

**Issue by ashutoshchaturvedi** [ankitkumar93/csc510-se-project#16]
How are we answering the db server need at client system. Are we going to install the db client also along with the plugin?

**Comment by ankitkumar93** [comment]
We have two options: a) request su mode from the user while installing and install mongo and make the db server run everytime the plugin boots before the db client connects
b) use a txt file or a json file and make the plugin read from it

**Comment by ankitkumar93** [comment]
which one do you think is more optimal?

**Comment by ankitkumar93** [comment]
everything is on the localhost for now! well see how it goes!
