### ISSUE TITLE
Server For Pulling Data off StackOverflow

### ISSUE THREAD

**Issue by ankitkumar93** [ankitkumar93/csc510-se-project#2]
Need to create a server using MEAN for pulling data through APIs off stackoverflow. This is the elementary requirement for the Data Analysis to follow and hence has to be done asap.

**Comment by ankitkumar93** [comment]
Me and Ayush would work on the server part I guess? as you guys are working on the NLTK part. This part needs to be finished ASAP!

**Comment by ayushgupta90** [comment]
Yes. Sounds Good.

**Comment by ankitkumar93** [comment]
No need to create a server for fetching data using API calls. We found their official dump:
https://archive.org/download/stackexchange
Need to Download these:
stackoverflow.com-Posts.7z  
stackoverflow.com-Tags.7z  
stackoverflow.com-Users.7z 

The size for download is about 8 gbs. Can someone download it overnight maybe? The speed is really low,so would take around 15 hrs or so...

**Comment by ankitkumar93** [comment]
Also now we can write a script to translate the XML with tags of python and corresponding posts and users into a DB for our use. So which DB to use now? Should we go with nosql ones (they are extremely fast) or the conventional mysql lampp stack.
