### ISSUE TITLE
Questions - Collection Structure

### ISSUE THREAD

**Issue by ankitkumar93** [ankitkumar93/csc510-se-project#29]
Hi guys can you give me the questions filtered structure for the collection. Thanks.

**Comment by ashutoshchaturvedi** [comment]
The tags present in data are:
1. Id
2. ViewCount
3. Title
4. LastEditDate
5. AnswerCount
6. Score
7. OwnerDisplayName
8. PostTypeId      --1 for Question/ 2 for Answers
9. OwnerUserId
10. Body
11. Tags
12. LastEditorUserId
13. LastActivityDate
14. CommentCount
15. AcceptedAnswerId
16. CreationDate
