### ISSUE TITLE
DB configuration

### ISSUE THREAD

**Issue by ayushgupta90** [ankitkumar93/csc510-se-project#3]
Need to figure out what data should be extracted using the APIs and how the DBs should be created (the structure of the DB). Also need to figure out which DB is compatible for our work (mongo, couch, cassandra, etc.)

**Comment by ankitkumar93** [comment]
As we only need one node for our server, Mongo DB is efficient enough and hence we should use MongoDB. I have worked with it before so it would be easier as well.

**Comment by ankitkumar93** [comment]
Also for the DB structure lets finalize the needed fields and add the structure up here. Then we can compare and contrast to arrive at an optimal structure.
