### ISSUE TITLE
Plugin Development

### ISSUE THREAD

**Issue by ankitkumar93** [ankitkumar93/csc510-se-project#6]
Need to learn how to code Sublime Text plugins. In python? or in javascript? Also need to figure out how to attach the recommendation system to it.

**Comment by ayushgupta90** [comment]
I think python is the right way to go. Just see the link below for reference:
https://clarknikdelpowell.com/blog/creating-sublime-text-3-plugins-part-1/

**Comment by ankitkumar93** [comment]
Lets get started on this part after we finish off our server part atleast. Also more focus should be on the recommendation system part for now as it is the base of our project.
